### PR TITLE
[Task]: Report on the success of the database import and the number of records imported

### LINKED ISSUE #109: [Task]: Report on the success of the database import and the number of records imported
### Summary

After #84 , `print()` or return using typer's api, a success message with the number of records or rows inserted. This should be available from the dataframe https://stackoverflow.com/a/15943975

### Acceptance criteria

- [ ] cli reports success or failure

### PR DESCRIPTION
**Pull request by aplybeah**
## Summary
Fixes #109 

## Changes proposed
* add print stmt

## Context for reviewers
After https://github.com/navapbc/simpler-grants-gov/pull/84 , print() or return using typer's api, a success message with the number of records or rows inserted.

### CODE REVIEW

**Review by acouch — APPROVED** [review]

**Review by coilysiren — COMMENTED** [review]
I feel like this should be logged, not printed?

**Comment by aplybeah** [comment]
@coilysiren this is more of a one liner follow up to this: https://github.com/navapbc/simpler-grants-gov/pull/130/files

**Comment by coilysiren** [comment]
Gotcha, unfortunately that doesnt explain why we are using a print statement here? Is something wrong with the logs? If the logs are broken we should fix them.

Alternatively if theres a special reason why this line must be a print statement, we should document that. But that is very rare, and I doubt we are in such a situation

**Comment by acouch** [comment]
@coilysiren The analytics app is setup using a Typer, unlike the API which just uses [poetry.scripts](https://github.com/navapbc/simpler-grants-gov/blob/main/api/pyproject.toml#L58) as an entry point. [Typer actually recommends](https://typer.tiangolo.com/tutorial/printing/) using `print()` statements and there are already some in the file.

The logging should probably happen in the app and the printing in the CLI entry point. At this point I'm not sure it makes sense to put more effort into creating a more ideal implementation and would just leave off the print statements for now.

**Pull request closed without merging**
